name: Test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v3
      with:
        go-version: "1.21.13"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v .
    
    - name: Test
      run:  go test ./...
